apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-storage
  labels:
    app: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi