pipeline {
    agent none

    environment{
        DOCKER_USERNAME = credentials('DOCKER_USERNAME')
        DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')
    }
    parameters {
        choice(
            choices: 'Eks\nKops\n',
            description: 'name of Cluster to connect to',
            name: 'name'
        )
    }
    stages {
        stage('Eks deployment') {
        when {
            beforeAgent true
            expression { 
                 params.name == 'Eks' 
                }
            }
        agent { 
            kubernetes{
                label 'jenkins-slave'
            }
        }
            steps{
                sh(script: """
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                """, returnStdout: true) 
                sh(script: """
                    git clone https://github.com/wahaj123/Eks-terraform-jenkins.git
                """, returnStdout: true)
                sh script: '''
                #!/bin/bash
                cd Eks-terraform-jenkins/Python-app
                docker build . --network=host -t wahaj123/hi-python
                '''
                sh(script: """
                    docker push wahaj123/hi-python
                """)
                sh script: '''
                #!/bin/bash
                curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
                chmod +x ./kubectl
                ./kubectl apply -f ./Eks-terraform-jenkins/Python-app/python-service.yaml
                ./kubectl apply -f ./Eks-terraform-jenkins/Python-app/python-deployment.yaml
                ''' 
            }
        }
        stage('Kops deployment') {
        when {
            beforeAgent true
            expression { 
                 params.name == 'Kops' 
                }
            }
        agent { 
            kubernetes{
                label 'jenkins-slave'
            }
        }
            steps{
                sh(script: """
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                """, returnStdout: true) 
                sh(script: """
                    git clone https://github.com/wahaj123/Eks-terraform-jenkins.git
                """, returnStdout: true)
                sh script: '''
                #!/bin/bash
                cd Eks-terraform-jenkins/Python-app
                docker build . --network=host -t wahaj123/hi-python
                '''
                sh(script: """
                    docker push wahaj123/hi-python
                """)
                sh script: '''
                #!/bin/bash
                curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
                chmod +x ./kubectl
                ./kubectl apply -f ./Eks-terraform-jenkins/Python-app/python-service.yaml
                ./kubectl apply -f ./Eks-terraform-jenkins/Python-app/python-deployment.yaml
                ''' 
            }
        }
    }
}